name: Periodic Health Check

on:
  push:
    branches:
      - master

jobs:
  run_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://pokedex-fso11-jfa.fly.dev/
